name: Terraform validate

on:
  pull_request:
    types:
      - opened
      - edited
      - ready_for_review
      - reopened
    branches:
      - develop

jobs:
  validate:
    name: Terraform validate
    runs-on: ubuntu-latest
    env:
      TF_VAR_allowed_account_id: ${{ secrets.ALLOWED_ACCOUNT_ID }}    
       
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Initialize Terraform
        run: |
          terraform init -input=false          

      - name: Validate Terraform
        id: plan
        continue-on-error: false
        run: |
          terraform validate -no-color
    
  automatic-merge-pr:        
      name: Merge to develop
      runs-on: ubuntu-latest
      needs: [ validate ]
      
      steps:
        - name: feature -> develop
          uses: "pascalgn/automerge-action@v0.15.3"          
          env:
            MERGE_LABELS: ""
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        
        - name: "PR Merged - Trigger Telegram alert"
          uses: appleboy/telegram-action@master
          if: success()
          with:
            to: ${{ secrets.TELEGRAM_CHANNEL_ID }}
            token: ${{ secrets.TELEGRAM_TOKEN }}
            message: |
              ${{ github.actor }} / [ ${{ github.repository }} ]
              📢 Pull request automatically merged into develop branch 📢       
  trigger-plan:
      name: Trigger plan
      uses: ./.github/workflows/terraform_plan.yml
      needs: [ automatic-merge-pr ]      
      secrets: inherit
