name: Terraform Plan

on:
  push:
    - main

jobs:
    terraform-plan:    
        name: Terraform validate / Staging        
        runs-on: ubuntu-latest
        env:
          TF_VAR_allowed_account_id: ${{ secrets.ALLOWED_ACCOUNT_ID }}    
           
        steps:
          - name: Check out code
            uses: actions/checkout@v2

          - name: Setup Terraform
            uses: hashicorp/setup-terraform@v1
            with:
              terraform_version: 1.2.1

          - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-region: us-east-1
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          - name: Initialize Terraform
            run: |
              terraform init -input=false          

          - name: Validate Terraform
            id: vt
            run: |
              terraform validate -no-color
          
          - name: Plan Terraform
            id: plan
            continue-on-error: false
            run: |
              terraform plan -input=false -no-color  
              
          - name: Apply Terraform
            id: apply
            continue-on-error: false
            run: |
                terraform apply -auto-approve
